// File storage on the local filesystem: <DATA_DIR>/storage/<bucket>/<key>.
//
// Buckets are public for reading (served from /files/<bucket>/<key>, like the
// former public Supabase buckets); writes need a session and pass the same
// checks as the former storage policies.
import { Hono, type Context, type Next } from 'hono';
import { serveStatic } from '@hono/node-server/serve-static';
import fs from 'node:fs';
import path from 'node:path';
import { db, asUser, uuid, ApiError, forbidden } from './db.ts';
import { env } from './env.ts';
import { requireSession } from './auth.ts';
import { canAccessProject } from './policies.ts';

interface Bucket {
  canWrite: (key: string) => boolean;
  canDelete: (key: string) => boolean;
}

// Piece attachment keys are "<pieceId>/<file>"; the piece must belong to a
// project the caller manages.
const canWritePieceFile = (key: string) =>
  Boolean(
    (
      db
        .prepare(`select exists (select 1 from pieces _pf where _pf.id = ? and ${canAccessProject('_pf.project_id')}) as v`)
        .get(key.split('/')[0]) as { v: number }
    ).v,
  );

const BUCKETS: Record<string, Bucket> = {
  photos: { canWrite: () => true, canDelete: () => false },
  'piece-files': { canWrite: canWritePieceFile, canDelete: canWritePieceFile },
};

const SEGMENT = /^[A-Za-z0-9][A-Za-z0-9._-]{0,199}$/;

const bucketOf = (name: string) => {
  const bucket = Object.hasOwn(BUCKETS, name) ? BUCKETS[name] : undefined;
  if (!bucket) throw new ApiError('Bucket not found', 404, 'NoSuchBucket');
  return bucket;
};

// Object keys are generated by the app (uuid + extension), so only plain
// segments are accepted — no traversal, no hidden files.
const filePath = (bucket: string, key: string) => {
  const segments = key.split('/');
  if (segments.length > 5 || !segments.every((s) => SEGMENT.test(s))) {
    throw new ApiError('Invalid object key', 400, 'InvalidKey');
  }
  return path.join(env.storageDir, bucket, ...segments);
};

const keyFromPath = (c: Context, prefix: string) => {
  const raw = c.req.path.slice(prefix.length).replace(/^\/+/, '');
  try {
    return decodeURIComponent(raw);
  } catch {
    throw new ApiError('Invalid object key', 400, 'InvalidKey');
  }
};

export const storageRoutes = new Hono();

// Upload: raw request body; `x-upsert: true` allows overwriting.
storageRoutes.post('/:bucket/*', async (c) => {
  const user = requireSession(c);
  const bucketName = c.req.param('bucket');
  const bucket = bucketOf(bucketName);
  const key = keyFromPath(c, `/api/storage/${bucketName}`);
  const target = filePath(bucketName, key);

  if (!asUser(user.id, () => bucket.canWrite(key))) {
    throw forbidden('new row violates row-level security policy');
  }
  if (Number(c.req.header('content-length') ?? 0) > env.maxUploadBytes) {
    throw new ApiError('The object exceeded the maximum allowed size', 413, 'EntityTooLarge');
  }
  const data = Buffer.from(await c.req.arrayBuffer());
  if (data.length > env.maxUploadBytes) {
    throw new ApiError('The object exceeded the maximum allowed size', 413, 'EntityTooLarge');
  }
  if (c.req.header('x-upsert') !== 'true' && fs.existsSync(target)) {
    throw new ApiError('The resource already exists', 409, 'Duplicate');
  }

  // Write to a temp file first so readers never see a partial upload.
  await fs.promises.mkdir(path.dirname(target), { recursive: true });
  const temp = `${target}.${uuid()}.tmp`;
  await fs.promises.writeFile(temp, data);
  await fs.promises.rename(temp, target);
  return c.json({ path: key, fullPath: `${bucketName}/${key}` });
});

// Delete: { paths: string[] }. Returns the keys that were removed.
storageRoutes.delete('/:bucket', async (c) => {
  const user = requireSession(c);
  const bucketName = c.req.param('bucket');
  const bucket = bucketOf(bucketName);
  const { paths } = (await c.req.json().catch(() => ({}))) as { paths?: unknown };
  if (!Array.isArray(paths)) throw new ApiError('paths must be an array', 400);

  const removed: { name: string }[] = [];
  for (const key of paths.map(String)) {
    const target = filePath(bucketName, key);
    if (!asUser(user.id, () => bucket.canDelete(key))) continue;
    try {
      await fs.promises.unlink(target);
      removed.push({ name: key });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
    }
  }
  return c.json(removed);
});

// ---------------------------------------------------------------------------
// Public read: /files/<bucket>/<key>[?download=<file name>]
// ---------------------------------------------------------------------------

// Types rendered inline. Everything else (HTML, SVG, scripts, …) is served as
// a download: the files share the app's origin and must never run script.
const INLINE_TYPES = /^(image\/(png|jpeg|gif|webp|avif)|audio\/|video\/|application\/pdf$|text\/plain)/;

const contentDisposition = (type: string, fileName: string) => {
  const fallback = fileName.replace(/[^\x20-\x7e]|["\\]/g, '_');
  return `${type}; filename="${fallback}"; filename*=UTF-8''${encodeURIComponent(fileName)}`;
};

const fileHeaders = async (c: Context, next: Next) => {
  const bucket = c.req.param('bucket') ?? '';
  if (!Object.hasOwn(BUCKETS, bucket)) return c.notFound();
  await next();
  if (c.res.status >= 400 || !c.res.headers.has('last-modified')) return;

  const headers = c.res.headers;
  const type = headers.get('content-type') ?? 'application/octet-stream';
  const download = c.req.query('download');
  const baseName = path.basename(c.req.path);
  if (!INLINE_TYPES.test(type)) {
    headers.set('Content-Type', 'application/octet-stream');
    headers.set('Content-Disposition', contentDisposition('attachment', download || baseName));
  } else if (download !== undefined) {
    headers.set('Content-Disposition', contentDisposition('attachment', download || baseName));
  }
  headers.set('X-Content-Type-Options', 'nosniff');
  // Chrome's PDF viewer refuses sandboxed documents; PDFs cannot run page script anyway.
  if (!type.startsWith('application/pdf')) headers.set('Content-Security-Policy', "sandbox; default-src 'none'");
  headers.set('Cache-Control', 'public, max-age=3600');
};

export const fileRoutes = new Hono();

fileRoutes.on(
  ['GET', 'HEAD'],
  '/:bucket/*',
  fileHeaders,
  serveStatic({
    root: env.storageDir,
    rewriteRequestPath: (p) => p.replace(/^\/files/, ''),
  }),
  (c) => c.notFound(),
);
