-- ============================================================================
-- Initial SQLite schema.
--
-- Consolidates the former Supabase/Postgres migrations (supabase/migrations/*)
-- into their final state. Conventions:
--   * ids are TEXT uuids generated by the uuid() function the server registers
--   * BOOLEAN columns store 0/1 and are returned to the browser as true/false
--   * JSON columns store JSON text and are returned parsed
--   * timestamps are ISO-8601 UTC strings (now_iso() / strftime)
-- Access control (the former RLS policies) lives in server/policies.ts.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Auth (private: never reachable through the generic data API)
-- ---------------------------------------------------------------------------

create table auth_users (
  id                 text primary key default (uuid()),
  email              text not null unique collate nocase,
  password_hash      text not null,
  email_confirmed_at text,
  created_at         text not null default (now_iso())
);

create table auth_sessions (
  token_hash   text primary key,
  user_id      text not null references auth_users (id) on delete cascade,
  created_at   text not null default (now_iso()),
  expires_at   text not null
);
create index auth_sessions_user_idx on auth_sessions (user_id);

-- One-time links sent by email: signup confirmation and email change.
create table auth_tokens (
  token_hash text primary key,
  user_id    text not null references auth_users (id) on delete cascade,
  kind       text not null check (kind in ('confirm_signup', 'email_change')),
  email      text not null,
  expires_at text not null
);

-- TOTP second factors. last_step blocks replaying a code within its window.
create table auth_factors (
  id         text primary key default (uuid()),
  user_id    text not null references auth_users (id) on delete cascade,
  secret     text not null,
  status     text not null default 'unverified' check (status in ('unverified', 'verified')),
  last_step  integer,
  created_at text not null default (now_iso())
);
create index auth_factors_user_idx on auth_factors (user_id);

-- ---------------------------------------------------------------------------
-- Accounts and settings
-- ---------------------------------------------------------------------------

create table app_users (
  id                  text primary key references auth_users (id) on delete cascade,
  email               text not null,
  name                text not null default '',
  is_admin            boolean not null default 0,
  can_manage_projects boolean not null default 0,
  all_projects        boolean not null default 1,
  can_access_club     boolean not null default 0,
  created_at          text not null default (now_iso())
);

create table app_settings (
  id                integer primary key default 1 check (id = 1),
  app_name          text not null default 'Anwesenheit',
  accent_color      text not null default '#efa100',
  icon              text default 'CheckSquare',
  language          text not null default 'en' check (language in ('de', 'en')),
  allow_self_signup boolean not null default 1
);
insert into app_settings (id) values (1);

-- ---------------------------------------------------------------------------
-- Projects
-- ---------------------------------------------------------------------------

create table projects (
  id                       text primary key default (uuid()),
  name                     text not null,
  description              text,
  image_url                text,
  status                   text not null default 'active' check (status in ('active', 'archived')),
  groups                   json not null default '[]',
  allow_account_access     boolean not null default 1,
  allow_account_checkin    boolean not null default 1,
  allow_account_signup     boolean not null default 1,
  allow_guest_checkin      boolean not null default 1,
  allow_guest_signup       boolean not null default 1,
  allow_participant_pieces boolean not null default 1,
  created_at               text not null default (now_iso()),
  created_by               text references app_users (id) on delete set null
);

-- Explicit project scope for managers with all_projects = false.
create table user_projects (
  user_id    text not null references app_users (id) on delete cascade,
  project_id text not null references projects (id) on delete cascade,
  primary key (user_id, project_id)
);
create index user_projects_user_idx on user_projects (user_id);

create table members (
  id         text primary key default (uuid()),
  project_id text not null references projects (id) on delete cascade,
  first_name text not null,
  last_name  text not null,
  group_name text,
  email      text,
  photo_url  text,
  status     text not null default 'active' check (status in ('active', 'archived', 'guest')),
  user_id    text references app_users (id) on delete set null,
  created_at text not null default (now_iso())
);
create index members_project_idx on members (project_id);
create index members_user_idx on members (user_id);
-- One linked member row per project and account.
create unique index members_project_user_uidx
  on members (project_id, user_id) where user_id is not null;

create table events (
  id         text primary key default (uuid()),
  project_id text not null references projects (id) on delete cascade,
  name       text not null,
  date       text,
  time       text,
  created_at text not null default (now_iso())
);
create index events_project_idx on events (project_id);

create table attendance (
  id        text primary key default (uuid()),
  event_id  text not null references events (id) on delete cascade,
  member_id text not null references members (id) on delete cascade,
  status    text not null default 'not_attended'
            check (status in ('not_attended', 'attended', 'excused')),
  is_guest  boolean not null default 0,
  unique (event_id, member_id)
);
create index attendance_event_idx on attendance (event_id);
create index attendance_member_idx on attendance (member_id);

-- ---------------------------------------------------------------------------
-- Public check-in
-- ---------------------------------------------------------------------------

create table event_checkins (
  event_id          text primary key references events (id) on delete cascade,
  token             text not null unique default (uuid()),
  is_active         boolean not null default 0,
  attendance_status text not null default 'attended'
                    check (attendance_status in ('attended', 'excused')),
  show_logo         boolean not null default 1,
  updated_at        text not null default (now_iso())
);

create table checkin_submissions (
  id                text primary key default (uuid()),
  event_id          text not null references events (id) on delete cascade,
  member_id         text references members (id) on delete set null,
  first_name        text not null,
  last_name         text not null,
  group_name        text not null,
  recognized        boolean not null,
  attendance_status text check (attendance_status in ('attended', 'excused')),
  submitted_at      text not null default (now_iso())
);
create index checkin_submissions_event_idx
  on checkin_submissions (event_id, submitted_at desc);
create index checkin_submissions_unrecognized_event_idx
  on checkin_submissions (event_id) where not recognized;

-- ---------------------------------------------------------------------------
-- Public registration
-- ---------------------------------------------------------------------------

create table registration_pages (
  id            text primary key default (uuid()),
  project_id    text not null references projects (id) on delete cascade,
  token         text not null unique default (uuid()),
  title         text not null,
  description   text not null default '',
  ask_email     boolean not null default 1,
  ask_group     boolean not null default 1,
  groups        json not null default '[]',
  is_active     boolean not null default 0,
  auto_transfer boolean not null default 0,
  created_at    text not null default (now_iso())
);
create index registration_pages_project_idx on registration_pages (project_id);

create table registrations (
  id                   text primary key default (uuid()),
  registration_page_id text not null references registration_pages (id) on delete cascade,
  first_name           text not null,
  last_name            text not null,
  email                text,
  group_name           text,
  member_id            text references members (id) on delete set null,
  transferred          boolean not null default 0,
  user_id              text references app_users (id) on delete set null,
  created_at           text not null default (now_iso())
);
create index registrations_page_idx on registrations (registration_page_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Club members
-- ---------------------------------------------------------------------------

create table club_members (
  id            text primary key default (uuid()),
  title         text,
  salutation    text,
  first_name    text not null,
  last_name     text not null,
  care_of       text,
  street        text,
  address_extra text,
  postal_code   text,
  city          text,
  country       text,
  email         text,
  phone         text,
  status        text not null default 'active' check (status in ('active', 'passive')),
  created_at    text not null default (now_iso())
);
create index club_members_name_idx on club_members (last_name, first_name);

-- ---------------------------------------------------------------------------
-- Pieces
-- ---------------------------------------------------------------------------

create table pieces (
  id         text primary key default (uuid()),
  project_id text not null references projects (id) on delete cascade,
  name       text not null,
  composer   text not null default '',
  position   integer not null default 0,
  created_at text not null default (now_iso())
);
create index pieces_project_idx on pieces (project_id, position);

create table piece_blocks (
  id          text primary key default (uuid()),
  piece_id    text not null references pieces (id) on delete cascade,
  type        text not null check (type in ('file', 'audio', 'link', 'text')),
  title       text not null default '',
  url         text,
  file_path   text,
  file_name   text,
  content     text,
  has_bars    boolean not null default 0,
  bars_start  integer,
  bars_end    integer,
  score_path  text,
  score_name  text,
  bar_anchors json not null default '{}',
  position    integer not null default 0,
  created_at  text not null default (now_iso()),
  check (not has_bars or (bars_start >= 1 and bars_end >= bars_start))
);
create index piece_blocks_piece_idx on piece_blocks (piece_id, position);

-- ---------------------------------------------------------------------------
-- Absence labels
-- ---------------------------------------------------------------------------

create table absence_labels (
  id         text primary key default (uuid()),
  project_id text not null references projects (id) on delete cascade,
  name       text not null,
  conditions json not null default '[]',
  is_public  boolean not null default 0,
  position   integer not null default 0,
  created_at text not null default (now_iso())
);
create index absence_labels_project_idx on absence_labels (project_id, position);

-- ---------------------------------------------------------------------------
-- Keep member names in sync with the account name.
-- The name is split at the last space: rtrim(s, <every non-space char of s>)
-- strips back to (and including) the last space.
-- ---------------------------------------------------------------------------

create trigger app_users_sync_member_names
after update of name on app_users
for each row
when trim(new.name) <> '' and new.name is not old.name
begin
  update members
  set first_name = case
        when instr(trim(new.name), ' ') = 0 then trim(new.name)
        else trim(rtrim(trim(new.name), replace(trim(new.name), ' ', '')))
      end,
      last_name = case
        when instr(trim(new.name), ' ') = 0 then ''
        else trim(substr(trim(new.name),
               length(rtrim(trim(new.name), replace(trim(new.name), ' ', ''))) + 1))
      end
  where user_id = new.id;
end;
